apiVersion: v1
kind: Secret
metadata:
  name: secret-env-consumer
  namespace: kafka
type: Opaque
data:
  PORT : 'MzAwMA==' #3000
  KAFKA_BROKERS : 'bXktY2x1c3Rlci1rYWZrYS1ib290c3RyYXA6OTA5Mg==' #my-cluster-kafka-bootstrap:9092
  KAFKA_TOPIC : 'dG9waWMtc29wZXMx' #topic-sopes1

#Los valores de las variables de entorno se deben codificar a base 64