apiVersion: v1
kind: Service
metadata:
  namespace: kafka
  name: service-consumer
spec:
  ports:
  - name: consumer-port
    port: 3000
    targetPort: 3000
  selector:
      name: deploy-consumer
  type: NodePort